author:  "R Kash" 
description:  "What's new for SAP on AWS" 
url:   "news.SAPonAWS.org" 
email:  "" 
title:  "What's new for SAP on AWS" 

theme: minima


header_pages:
  - _pages/homepage.md
  - _pages/docs.md
  - _pages/blogs.md
 

include:
    - _pages
    


plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
 
 exclude:
  - LICENSE
  - README.md
  - Makefile
