author:  "" 
description:  "What's new for SAP on AWS" 
url:   "news.SAPonAWS.org" 
email:  "" 
title:  "" 

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one



header_pages:
  - _pages/homepage.md
  - _pages/docs.md
  - _pages/blogs.md
 

include:
    - _pages
    


plugins:
 - jekyll-feed
 - jekyll-seo-tag
