author:  "" 
description:  "" 
url:   "news.SAPonAWS.org" 
email:  "" 
title:  "What's new for SAP on AWS" 

theme: minima

header_pages:
  - _pages/index.md
  - _pages/blogs.md
  - _pages/docs.md

 
include:
    - _pages
    
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
